### PR TITLE
bump node to v14

### PR DESCRIPTION
**Pull request by jonhill13**
### Author
- [x] Story Book has been rebuilt (new build artifacts in `/docs`)
- [x] Components have been rebuilt (new build artifacts in `/dist`)

👆These can be done by executing `npm run build` and committing the build artifacts.

- [N/A] All new components have been exported in `/index.js` `(if applicable)`
- [N/A] Design Review Complete
- [x] Relevant Draft release notes have been updated describing these changes ([use this template](https://github.com/fedspendingtransparency/data-transparency-ui/blob/master/release_notes_template.md) to document your changes) `(if applicable)`
- [N/A] Integration Status Updated on relevant documentation page `(if applicable)`
- [N/A] `index.d.ts` updated with new prop types defined for new components. `(if applicable)`

### Reviewer
- [x] Code review

### CODE REVIEW

**Review by brett-varney — CHANGES_REQUESTED** [review]
Locally I'm getting:

found 48 vulnerabilities (31 moderate, 17 high)

...and audit fix didn't do anything. I'm reluctant to accept this as is...

**Comment by jonhill13** [comment]
@brett-varney installing with node 12 `found 806 vulnerabilities (772 moderate, 34 high)`, 
after running fix `found 61 vulnerabilities (46 moderate, 15 high) in 2345 scanned packages`. By your logic we should remove this library as a dependency from the USASpending website.

**Review by brett-varney — APPROVED** [review]
works, just has merge conflict

**Comment by jonhill13** [comment]
@brett-varney Thank you. I want to merge this last as to not effect anyone else having to migrate their branch to node 14.

**Pull request merged**
